# 说明：插件默认启用默认配置，修改请参考配置文档，修改的部分会自动覆盖默认配置。
# 全局配置参考 https://m7s.live/guide/config.html
# 插件配置参考各个插件的文档
# 插件都有一个enable配置，如果为false则不启用该插件，默认为true即不需要配置。

# global:
  # secret: "123456"
  # http:
  #   listenaddrtls: :8081
  #   certfile: monibuca.com.pem
  #   keyfile: monibuca.com.key
# record:
#   mp4:
#     autorecord: true
#     fragment: 20
# webtransport:
#   enable: false
#   certfile: monibuca.com.pem
#   keyfile: monibuca.com.key
# rtsp:
#   pull:
#     pullonstart: true
#     pulllist:
#       live/rtsp : rtsp://admin:aaa123456@airiot.link:18554/Streaming/Channels/101
# hls:
#   enable: false
#   pull:
#     pullonstart: true
#     pulllist:
#       live/hls: http://111.40.196.27/PLTV/88888888/224/3221225548/index.m3u8
