# global:
  # secret: "123456"
  # consoleurl: "wss://console.monibuca.com/test"
  # http:
  #   listenaddrtls: :8081
  #   certfile: monibuca.com.pem
  #   keyfile: monibuca.com.key
# record:
#   mp4:
#     autorecord: false
# webtransport:
#   enable: false
#   certfile: monibuca.com.pem
#   keyfile: monibunica.com.key
# rtsp:
#   pull:
#     pullonstart: true
#     pulllist:
#       live/test : rtsp://admin:aaa123456@airiot.link:18554/Streaming/Channels/101
#   push:
#     pushlist:
#       live/test : rtsp://localhost:8554/live/test
# hls:
#   pull:
#     pullonstart: true
#     pulllist:
#       live/test : http://111.40.196.27/PLTV/88888888/224/3221225548/index.m3u8