name: Go

on:
  push:
    branches: [ 3.0 ]
  pull_request:
    branches: [ 3.0 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -o linux
      
    - name: Tar
      run: tar -zcvf linux.tgz linux config.toml
      
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
          local: /home/runner/work/monibuca/monibuca/linux.tgz
          remote: /opt/dexter/linux.tgz
          host: monibuca.com
          username: root
          privateKey: ${{ secrets.PEM }}
  build2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -o windows.exe
            
    - name: Tar
      run: tar -zcvf windows.tgz windows.exe config.toml
      
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
          local: D:\\a\\monibuca\\monibuca\\windows.tgz
          remote: /opt/dexter/windows.tgz
          host: monibuca.com
          username: root
          privateKey: ${{ secrets.PEM }}
  build3:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -o mac

    - name: Tar
      run: tar -zcvf mac.tgz mac config.toml

    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
          local: /Users/runner/work/monibuca/monibuca/mac.tgz
          remote: /opt/dexter/mac.tgz
          host: monibuca.com
          username: root
          privateKey: ${{ secrets.PEM }}
