name: Go

on:
  push:
    branches: [ 3.0 ]
  pull_request:
    branches: [ 3.0 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -o linux
      
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
          local: linux
          remote: /opt/dexter/
          host: 49.234.82.99
          username: root
          privateKey: ${{ secrets.PEM }}
  build2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -o windows.exe
      
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
          local: windows.exe
          remote: /opt/dexter/
          host: 49.234.82.99
          username: root
          privateKey: ${{ secrets.PEM }}
  build3:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -o mac
      
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
          local: mac
          remote: /opt/dexter/
          host: 49.234.82.99
          username: root
          privateKey: ${{ secrets.PEM }}
