name: Go

on:
  create:
    tags:
      - v4*
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
          fetch-depth: 1

    - name: Set up Env
      run: echo "version=${GITHUB_REF:11}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: runner.os−go−{ { hashFiles('**/go.sum') } }
        restore-keys: ${{ runner.os }}-go-        

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout m7s-import
      uses: actions/checkout@v3
      with:
        repository: langhuihui/m7s-import
        path: m7s-import
        fetch-depth: 1

    - name: Add bin to m7s-import
      if: success() && startsWith(github.ref, 'refs/tags/')
      run:  |
        cd m7s-import
        ls .
        mkdir -p apps/m7s-website/src/public/bin
        cp ../dist/m7s_${{ env.version }}_windows_amd64.tar.gz apps/m7s-website/src/public/bin/m7s_windows_amd64.tar.gz
        cp ../dist/m7s_${{ env.version }}_darwin_amd64.tar.gz  apps/m7s-website/src/public/bin/m7s_darwin_amd64.tar.gz 
        cp ../dist/m7s_${{ env.version }}_darwin_arm64.tar.gz  apps/m7s-website/src/public/bin/m7s_darwin_arm64.tar.gz 
        cp ../dist/m7s_${{ env.version }}_linux_amd64.tar.gz   apps/m7s-website/src/public/bin/m7s_linux_amd64.tar.gz 
        cp ../dist/m7s_${{ env.version }}_linux_arm64.tar.gz   apps/m7s-website/src/public/bin/m7s_linux_arm64.tar.gz 

        git config --global user.name 'langhuihui' 
        git config --global user.email '178529795@qq.com'
        git add -A
        git commit -m '[automated commit] add bin & GitHub workflow'
        git remote set-url --push origin https://178529795@qq.com:${{ secrets.TOKEN }}@github.com/langhuihui/m7s-import
        git push
